name: Build, Test, and Package on PR to Main

on:
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
